name: sentry-dart
on: [workflow_dispatch, push]

jobs:
  build:
    name: Build ${{matrix.sdk}} on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
        working-directory: ./dart
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        sdk: [stable]
    steps:
      - uses: dart-lang/setup-dart@fedb1266e91cf51be2fdb382869461a434b920a3 # pin@v1
        with:
          sdk: ${{ matrix.sdk }}
      - uses: actions/checkout@v4

      - name: Test (VM and browser)
        run: |
          dart pub get          
          dart test -p vm --test-randomize-ordering-seed=random --chain-stack-traces test/example_web_compile_test.dart


